# Generated by Django 3.2.4 on 2021-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='url',
        ),
        migrations.AddField(
            model_name='workshop',
            name='zoom_link',
            field=models.CharField(blank=True, help_text='Zoom link and password to the workshop.', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshopphoto',
            name='photo',
            field=models.ImageField(help_text='The photo taken by the user during the workshop.', max_length=200, upload_to='workshop_photos'),
        ),
    ]
