# Generated by Django 3.2.4 on 2021-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20210627_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='zoom_password',
            field=models.CharField(blank=True, help_text='Zoom password to the workshop.', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='zoom_link',
            field=models.CharField(blank=True, help_text='Zoom link to the workshop.', max_length=200),
        ),
    ]
