# Generated by Django 3.2.4 on 2021-06-27 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='The profile picture of the user.', max_length=200, upload_to='profile_pictures')),
                ('name', models.CharField(help_text='The name of the user.', max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='The country you live in.', max_length=2)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Asia/Singapore', help_text='The timezone to use as reference.')),
                ('interests', models.ManyToManyField(blank=True, help_text='The tags that you are interested in.', related_name='interested_users', to='workshops.Tag')),
                ('user', models.OneToOneField(help_text='The user to which the profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
